import { readdir, writeFile } from "node:fs/promises";
import { extname, join } from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const root = join(fileURLToPath(new URL(".", import.meta.url)), "..");
const albumsRoot = join(root, "public", "albums");
const outFile = join(root, "src", "albums.generated.ts");
const allowed = new Set([".jpg", ".jpeg", ".png", ".webp"]);

function encodePath(album, file) {
  return `./albums/${encodeURIComponent(album)}/${encodeURIComponent(file)}`;
}

function compareNames(a, b) {
  return a.localeCompare(b, "en", { numeric: true, sensitivity: "base" });
}

const albums = (await readdir(albumsRoot, { withFileTypes: true }))
  .filter((entry) => entry.isDirectory())
  .map((entry) => entry.name)
  .sort((a, b) => {
    const rank = (name) => (name === "精修" ? 0 : name === "初修" ? 1 : name === "产品" ? 2 : 3);
    const delta = rank(a) - rank(b);
    return delta !== 0 ? delta : compareNames(a, b);
  });

const lines = [
  "// Generated by scripts/catalog-albums.mjs. Do not edit by hand.",
  `export type GeneratedPhoto = { id: string; src: string; alt: string; w: number; h: number };`,
  `export const photosByAlbum: Record<string, GeneratedPhoto[]> = {`,
];

for (const album of albums) {
  const files = (await readdir(join(albumsRoot, album)))
    .filter((file) => allowed.has(extname(file).toLowerCase()))
    .sort(compareNames);

  lines.push(`  ${JSON.stringify(album)}: [`);
  for (const file of files) {
    const meta = await sharp(join(albumsRoot, album, file)).metadata();
    const w = meta.width ?? 0;
    const h = meta.height ?? 0;
    const id = file;
    const alt = `${album} ${file.replace(/\.[^.]+$/, "")}`;
    lines.push(
      `    { id: ${JSON.stringify(id)}, src: ${JSON.stringify(encodePath(album, file))}, alt: ${JSON.stringify(alt)}, w: ${w}, h: ${h} },`,
    );
  }
  lines.push(`  ],`);
  console.log(`${album}: ${files.length} photos`);
}

lines.push(`};`, "");
await writeFile(outFile, lines.join("\n"));
console.log(`wrote ${outFile}`);
